name: Deploy GHCR

on:
  workflow_run:
        workflows: ['Trivy Scan']
        types: [completed]
        branches:
            - 'main'

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/kffans/app:latest \
                --cache-from type=registry,ref=ghcr.io/kffans/app:latest \
                --cache-to type=registry,ref=ghcr.io/kffans/app:latest,mode=max \
                --platform linux/amd64,linux/arm64
              docker push ghcr.io/kffans/app:latest
