name: Trivy Scan
on: [push, pull_request]
 
permissions:
  actions: read
  security-events: write
  contents: read
  packages: write


jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build --tag ghcr.io/kffans/app:latest .
          - name: Run Trivy vulnerability scan
            uses: aquasecurity/trivy-action@0.30.0
            with:
              image-ref: 'ghcr.io/kffans/app:latest'
              format: 'sarif'
              exit-code: 0
              severity: 'CRITICAL,HIGH'
              output: 'trivy-results.sarif'
          - name: Upload Trivy scan results to GitHub Security tab
            uses: github/codeql-action/upload-sarif@v3
            with:
                sarif_file: 'trivy-results.sarif'

